spring:
#  数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
#    druid配置
    druid:
      url: jdbc:mysql://132.232.87.31:53306/myblog?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: Lihanlu123++.123
#      初始连接数
      initial-size: 10
#      最大连接数
      max-active: 100
#      最小连接数
      min-idle: 0
#      最长等待时间
      max-wait: 60000
#      开启缓存
      pool-prepared-statements: true
#      启用PSCache后，指定每个连接上PSCache的大小
      max-pool-prepared-statement-per-connection-size: 20
#      检测连接的间隔时间，若连接空闲时间 >= minEvictableIdleTimeMillis，则关闭物理连接
      time-between-eviction-runs-millis: 60000
#      连接保持空闲而不被驱逐的最小时间(ms)
      min-evictable-idle-time-millis: 300000
#      申请连接时检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效（不影响性能）
      test-while-idle: true
#      申请连接时不检测连接是否有效
      test-on-borrow: false
#      归还连接时不检测连接是否有效
      test-on-return: false
#      是否启用StatViewServlet默认值true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
#redis的配置
  redis:
#    redis数据库索引（默认为0）
    host: 127.0.0.1
#    连接端口
    port: 6379
#    连接密码
    password: root
#    连接池超时时长
    timeout: 6s
    lettuce:
      pool:
        max-active: 1000 #连接池最大连接数量
        max-wait: -1ms #连接池最大阻塞等待时间，无
        max-idle: 10 #连接池最大空闲连接
        min-idle: 5 #连接池最小空闲连接
  # rabbitMQ配置
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
mybatis-plus:
#
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    开发环境刷新mapper
  global-config:
    refresh: true